language: go
go: 1.x

env:
  - PATH=$PATH:$GOPATH/bin GO111MODULE=on

install:
  - go mod download

script:
  - go test -v

before_deploy:
  - bin/deploy-compile.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ChIuSkI7nHKGDbHlRSBdu4yVyQtqFWzrBK5GIoNAHlY/R+TkYwY+e1zCFm98PIc8t93OiT4U7SZ0FLL+sI6eQDaq9WCza9kVlHURLDDWFh/J3GVJwe7kWgY5nW0AES8nIkTqhuvZjWMIpChiPUOU70wDk2s2MbxIk+uQqlWpQztn3vj82zBbzOhOyv3sUaQKetU09Nu9siOH5Tw7E98wQqX7gFtJ9oWqn8giSAd+ThYGImw60BWJFSAq1JE2xu5sdueOga11agKG3K+Vv6yxBuyjKAhFV7KFYfxLZddw6mbf5FGR5O2LvvbKHtsP+mx3ZuADzOh1UmtZhNoL4PRV2MLDfXSth0OXJLe+/xDSxo8waOkvdvGS03BM1MIVfVyuDAX9rE5fFHFgQNU3iewjDCcbGQVTGyhyUF8I4RXU7FcvMGHa+pTVlgvET94B+cfPIbJbGncFfccjFUoUmcMjopxItHmer5MffeOe26O1lJkNtLfEMctlGd8Y6eJZfcMO0mjQhqEedKdIdbqORGFcILfZ0tNo8X82XoTMPG+sPJqB9XioqMzK+5dpEBYRQLvZpE/bSBDFXkLwJGVj5/Pk3AJhgTIJTzCjTzyOup2hP4hTg+FdgP5Ff9Y8Ro3uS2zvBEGMw77xEe/zDu4kGZ6aiQNzEK+2n81WAs2dbi17RAo=
  file_glob: true
  file: target/*
  on:
    repo: nickw444/cf-ddns
    tags: true
